### ISSUE TITLE
Mesh bed saves as "auto" instead of "default" 

### ISSUE THREAD

**Issue by THEGxHOxST** [xblax/flashforge_adm5_klipper_mod#108]
Mesh bed saves as "auto" instead of "default" which doesn't allow MainSail to load it by default.
Fixed by changes in Macros.cfg

From
[gcode_macro AUTO_BED_LEVEL]
gcode:
    {% set bed_temp = params.BED_TEMP|default(60)|float %}
    {% set extruder_temp = params.EXTRUDER_TEMP|default(200)|float %}
    {% set profile = params.PROFILE|default("auto") %}

To
[gcode_macro AUTO_BED_LEVEL]
gcode:
    {% set bed_temp = params.BED_TEMP|default(60)|float %}
    {% set extruder_temp = params.EXTRUDER_TEMP|default(200)|float %}
    {% set profile = params.PROFILE|default("default") %}

I also recommend changing the probe z offset to -0.35

**Comment by xblax** [comment]
That's not really a bug but intended behavior. In general, a created Mesh should not be loaded automatically just because someone presses the Save Config button (maybe even to save something else) - because then loading the mesh automatically is more like an unintended side effect.

Klipper did even remove that behavior from from 0.12. Bed Mesh depends on Bed Temp, Nozzle, Print Surface etc - it's better to not make any assumptions on that, therefore all meshes are created by default as 'auto'. If and when a saved mesh should be loaded automatically is up to the user user to configure.

The topic can also be further discusses in the discussion section, i.e. here: https://github.com/xblax/flashforge_adm5_klipper_mod/discussions/106

Regarding the z-Offset: This issue here is still open for finding the optimal value: https://github.com/xblax/flashforge_adm5_klipper_mod/issues/73

But in my experience -0.35 is way too much. We have -0.25 as a default and I started to prints with -0.15 lately, because that gives a bit nicer and more dense first layers.
