### ISSUE TITLE
SAVE_CONFIG section 'stepper_z' option 'position_endstop' conflicts with included value

### ISSUE THREAD

**Issue by AJolly** [xblax/flashforge_adm5_klipper_mod#113]
Since the position_endstop is in printer.base.cfg, it can't be updated.

This is after running a print, adjusting z via the screen, and attempting to save.

**Comment by THEGxHOxST** [comment]
I had to use probe off set, I believe its because the beds endstop is at the bottom.
probe offest can be found in printer.cfg and klipper screen.

**Comment by xblax** [comment]
The answer from @THEGxHOxST is correct. Because the bed end stop is at the bottom (and also because the probe is not the end stop), it does not make sense to save the offset to the endstop (it would just lead to accumulated offset error over time).

This was already discussed here: https://github.com/xblax/flashforge_adm5_klipper_mod/discussions/61

I will create a separate issue to add section about bed leveling to the documentation. This should also be explained there.
