### ISSUE TITLE
Buzzer support

### ISSUE THREAD

**Issue by xblax** [xblax/flashforge_adm5_klipper_mod#20]
### Discussed in https://github.com/xblax/flashforge_adm5_klipper_mod/discussions/15

The integrated buzzer should be usable for the mod, i.e. to notify print end or errors.

This could be done via a standalone executable or python script that is called from Macros as a G-Code shell command: 
https://github.com/dw-0/kiauh/blob/master/docs/gcode_shell_command.md

**Comment by consp** [comment]
Hmm, revert is then in order (sorry). But the bigger problem is then why a clean rebuild did not build the buildroot (yes I also merged that master and redid the config). Could be I did something wrong but I'm pretty sure I rebased everything, will check tonight what went wrong since it might also be wrong in the klipperscreen build. Good reason to look into the method for building/patching buildroot. 

> Reason for this that busybox setsid seems to not fork into background.

I had no issues with it and it. Afaik it always forks if you are not the group leader (which the process most likely is not).
